name: fhir_db
description: Using the Sembast DB to store fhir resources
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  sembast_sqflite: ^0.2.0+2
  sembast: ^2.4.5
  path_provider: ^1.6.11
  fhir: ^0.0.5


dev_dependencies:
