name: fhir_db
description: Using the Sembast DB to store fhir resources
version: 0.0.1
author:
homepage:

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  sembast: ^2.4.5
  fhir: ^0.0.5
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'


dev_dependencies:
