name: fhir_db
description: A wrapper for Sembast and SQFlite to enable easy, local and secure storage of fhir resources
version: 0.0.1
homepage: https://www.fhirfli.dev/
repository: https://github.com/Dokotela/fhir_db

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^1.3.0
  sembast_sqflite: ^0.2.0+2
  sembast: ^2.4.5
  fhir: ^0.0.8
  encrypt: '>=3.1.0'
  crypto: '>=2.0.6'
  path_provider: ^1.6.11

dev_dependencies:
